const GARMIN = {
  "atualizado": "09/07/2026 às 23:05h",
  "hoje": "2026-07-09",
  "body_battery": 32,
  "bb_max": 60,
  "bb_min": 20,
  "bb_feedback_cor": "red",
  "bb_feedback_msg": "⚠️ Baixo — treino leve",
  "steps": "5.934",
  "steps_goal": "7.530",
  "steps_pct": 79,
  "steps_feedback_cor": "yellow",
  "steps_feedback_msg": "⚡ Bom progresso",
  "fc_repouso": 73,
  "fc_feedback_cor": "yellow",
  "fc_feedback_msg": "⚡ Atenção",
  "estresse": 35,
  "spo2_min": 82,
  "spo2_media": 95.0,
  "spo2_feedback_cor": "red",
  "spo2_feedback_msg": "🔴 Crítico — investigar",
  "hrv_val": 27,
  "hrv_status": "UNBALANCED",
  "calorias": 432.0,
  "sono_h": 7.5,
  "sono_score": 79,
  "sono_qualidade": "FAIR",
  "sono_profundo": 99,
  "sono_rem": 100,
  "sono_leve": 252,
  "acordou": 1,
  "spo2_sono": 96.0,
  "spo2_sono_min": 82,
  "sono_feedback_cor": "green",
  "sono_feedback_msg": "✅ Sono bom",
  "frase_sono": "Noite razoável — 7.5h dormidas, score 79. Deu pra recuperar mas não foi o ideal. Atenção à intensidade hoje.",
  "orientacao_cor": "yellow",
  "orientacao_icon": "⚠️",
  "orientacao_titulo": "Treino moderado — sem forçar",
  "orientacao_texto": "Sinais de recuperação incompleta. Musculação com carga reduzida · Cardio zona 2 · Sem corrida forte hoje.",
  "treino_nome_hoje": "Peito + Ombro + Tríceps",
  "atividade_feita": true,
  "cardio_feito": false,
  "musculacao_feita": true,
  "minutos_ativos_hoje": 84,
  "alerta_treino": "",
  "alerta_treino_urgente": false,
  "hora_brasilia": 20
};
