const GARMIN = {
  "atualizado": "09/09/2026 às 18:20h",
  "resumo_personal": "📋 Resumo diário — Poli (09/09/2026 às 18:20h)\n\n⚡ Body Battery: 62/100 — ✅ Bom — pode treinar\n😴 Sono: 7.8h · score 82 — ✅ Sono bom\n❤️ FC repouso: 70 bpm\n🚶 Passos: 368/7930 (5%)\n🫁 SpO2 mínimo: 88%\n📊 Estresse médio: 24/100\n\n🏋️ Treino de hoje: Quadríceps + Adução\n🎯 Orientação: Pode treinar! Siga a ficha do dia. — Body Battery e sono em bom nível. Siga a ficha semanal normalmente. Monitore a FC durante o treino.",
  "tag_sono": "Sono Bom",
  "tag_cor": "green",
  "frase_claude_noite": "Boa noite! 7.8h de sono com score 82. Body Battery ao acordar em boa forma. Aproveite o dia com intensidade normal.",
  "detalhe_noite": "Sono REM: 102 min · SpO2 mínimo: 88% · Body Battery: 62 · Estresse médio: 24/100",
  "tag_semana": "Atenção",
  "tag_cor_semana": "red",
  "frase_claude_semana": "SpO2 abaixo de 90% em 7 das últimas 7 noites — padrão consistente de dessaturação. Prioridade: consulta com pneumologista e polissonografia.",
  "detalhe_semana": "Score médio: 75/100 · SpO2 abaixo de 90%: 7/7 noites · SpO2 mínimo do período: 85% · Período: 02/09 → 09/09/2026",
  "data_hoje_fmt": "09/09/2026",
  "data_inicio_fmt": "02/09",
  "hoje": "2026-09-09",
  "body_battery": 62,
  "bb_max": 65,
  "bb_min": 16,
  "bb_feedback_cor": "green",
  "bb_feedback_msg": "✅ Bom — pode treinar",
  "steps": "368",
  "steps_goal": "7.930",
  "steps_pct": 5,
  "steps_feedback_cor": "red",
  "steps_feedback_msg": "⚠️ Muito parada hoje",
  "fc_repouso": 70,
  "fc_feedback_cor": "yellow",
  "fc_feedback_msg": "⚡ Atenção",
  "estresse": 24,
  "spo2_min": 88,
  "spo2_media": 98.0,
  "spo2_feedback_cor": "red",
  "spo2_feedback_msg": "⚠️ Abaixo de 90% — atenção",
  "hrv_val": 28,
  "hrv_status": "BALANCED",
  "calorias": 16.0,
  "calorias_repouso": 516.0,
  "calorias_total": 532.0,
  "sono_h": 7.8,
  "sono_score": 82,
  "sono_qualidade": "GOOD",
  "sono_profundo": 66,
  "sono_rem": 102,
  "sono_leve": 300,
  "acordou": 0,
  "spo2_sono": 98.0,
  "spo2_sono_min": 88,
  "sono_feedback_cor": "green",
  "sono_feedback_msg": "✅ Sono bom",
  "frase_sono": "Boa noite de sono! Você dormiu 7.8h com score 82 — seu corpo recuperou bem. Aproveite o dia.",
  "orientacao_cor": "green",
  "orientacao_icon": "💪",
  "orientacao_titulo": "Pode treinar! Siga a ficha do dia.",
  "orientacao_texto": "Body Battery e sono em bom nível. Siga a ficha semanal normalmente. Monitore a FC durante o treino.",
  "historico_spo2": [
    {
      "data": "2026-09-08",
      "spo2_med": 98.0,
      "spo2_min": 86,
      "sono_score": 66,
      "resp_min": 17.0,
      "alerta": true
    },
    {
      "data": "2026-09-07",
      "spo2_med": 97.0,
      "spo2_min": 85,
      "sono_score": 69,
      "resp_min": 10.0,
      "alerta": true
    },
    {
      "data": "2026-09-06",
      "spo2_med": 96.0,
      "spo2_min": 85,
      "sono_score": 67,
      "resp_min": 16.0,
      "alerta": true
    },
    {
      "data": "2026-09-05",
      "spo2_med": 97.0,
      "spo2_min": 87,
      "sono_score": 69,
      "resp_min": 14.0,
      "alerta": true
    },
    {
      "data": "2026-09-04",
      "spo2_med": 97.0,
      "spo2_min": 85,
      "sono_score": 86,
      "resp_min": 16.0,
      "alerta": true
    },
    {
      "data": "2026-09-03",
      "spo2_med": 97.0,
      "spo2_min": 85,
      "sono_score": 85,
      "resp_min": 15.0,
      "alerta": true
    },
    {
      "data": "2026-09-02",
      "spo2_med": 98.0,
      "spo2_min": 86,
      "sono_score": 84,
      "resp_min": 15.0,
      "alerta": true
    },
    {
      "data": "2026-09-01",
      "spo2_med": 97.0,
      "spo2_min": 87,
      "sono_score": 83,
      "resp_min": 14.0,
      "alerta": true
    },
    {
      "data": "2026-08-31",
      "spo2_med": 96.0,
      "spo2_min": 90,
      "sono_score": 75,
      "resp_min": 15.0,
      "alerta": false
    }
  ],
  "spo2_noites_abaixo_90": 8,
  "spo2_min_absoluto": 85,
  "spo2_min_media": 86.2,
  "treino_nome_hoje": "Quadríceps + Adução",
  "atividade_feita": true,
  "cardio_feito": false,
  "musculacao_feita": true,
  "minutos_ativos_hoje": 98,
  "alerta_treino": "",
  "alerta_treino_urgente": false,
  "hora_brasilia": 15
};
