const GARMIN = {
  "atualizado": "17/07/2026 às 14:27h",
  "hoje": "2026-07-17",
  "body_battery": 70,
  "bb_max": 73,
  "bb_min": 22,
  "bb_feedback_cor": "green",
  "bb_feedback_msg": "✅ Bom — pode treinar",
  "steps": "580",
  "steps_goal": "6.010",
  "steps_pct": 10,
  "steps_feedback_cor": "red",
  "steps_feedback_msg": "⚠️ Muito parada hoje",
  "fc_repouso": 66,
  "fc_feedback_cor": "green",
  "fc_feedback_msg": "✅ Saudável",
  "estresse": 21,
  "spo2_min": 86,
  "spo2_media": 96.0,
  "spo2_feedback_cor": "red",
  "spo2_feedback_msg": "🔴 Crítico — investigar",
  "hrv_val": 30,
  "hrv_status": "BALANCED",
  "calorias": 17.0,
  "sono_h": 7.6,
  "sono_score": 82,
  "sono_qualidade": "GOOD",
  "sono_profundo": 116,
  "sono_rem": 93,
  "sono_leve": 246,
  "acordou": 0,
  "spo2_sono": 96.0,
  "spo2_sono_min": 86,
  "sono_feedback_cor": "green",
  "sono_feedback_msg": "✅ Sono bom",
  "frase_sono": "Boa noite de sono! Você dormiu 7.6h com score 82 — seu corpo recuperou bem. Aproveite o dia.",
  "orientacao_cor": "green",
  "orientacao_icon": "💪",
  "orientacao_titulo": "Pode treinar! Siga a ficha do dia.",
  "orientacao_texto": "Body Battery e sono em bom nível. Siga a ficha semanal normalmente. Monitore a FC durante o treino.",
  "treino_nome_hoje": "Glúteo ⭐",
  "atividade_feita": false,
  "cardio_feito": false,
  "musculacao_feita": false,
  "minutos_ativos_hoje": 0,
  "alerta_treino": "",
  "alerta_treino_urgente": false,
  "hora_brasilia": 11
};
